// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5smKHYg5ME2T4is6FkAAhFt2hn-9fsM',
    appId: '1:169118692919:web:7399a9a633d1efa087b1b2',
    messagingSenderId: '169118692919',
    projectId: 'apptodo-c0d0a',
    authDomain: 'apptodo-c0d0a.firebaseapp.com',
    storageBucket: 'apptodo-c0d0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwg-JuEg6ZGl1bDM80TVywRTUChB-dSS0',
    appId: '1:169118692919:android:3e306715670ef7a287b1b2',
    messagingSenderId: '169118692919',
    projectId: 'apptodo-c0d0a',
    storageBucket: 'apptodo-c0d0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmdUsZdt18GktUiTnlo9RZM4Fk-x_ZkA',
    appId: '1:169118692919:ios:ef22026f57fe0ef387b1b2',
    messagingSenderId: '169118692919',
    projectId: 'apptodo-c0d0a',
    storageBucket: 'apptodo-c0d0a.firebasestorage.app',
    iosBundleId: 'com.example.appToDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqmdUsZdt18GktUiTnlo9RZM4Fk-x_ZkA',
    appId: '1:169118692919:ios:ef22026f57fe0ef387b1b2',
    messagingSenderId: '169118692919',
    projectId: 'apptodo-c0d0a',
    storageBucket: 'apptodo-c0d0a.firebasestorage.app',
    iosBundleId: 'com.example.appToDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz5smKHYg5ME2T4is6FkAAhFt2hn-9fsM',
    appId: '1:169118692919:web:9807ad110ce8504a87b1b2',
    messagingSenderId: '169118692919',
    projectId: 'apptodo-c0d0a',
    authDomain: 'apptodo-c0d0a.firebaseapp.com',
    storageBucket: 'apptodo-c0d0a.firebasestorage.app',
  );
}
